DROP DATABASE IF EXISTS CPNV

CREATE DATABASE IF NOT EXISTS CPNV

USE CPNV

CREATE TABLE Flieres (
    Nom VARCHAR(256) NOT NULL,
    Code VARCHAR(256) PRIMARY KEY,
    Site VARCHAR(256) NOT NULL
);

CREATE TABLE Classes (
    Nom VARCHAR(256),
    Salle_principale VARCHAR(256) NOT NULL,
    Code VARCHAR(256),
    FOREIGN KEY (Code) REFERENCES Flieres(Code)
);

